### ISSUE TITLE
Bad types in 2.7.1

### ISSUE THREAD

**Issue by alecmev** [eslint-stylistic/eslint-stylistic#526]
### Validations

- [X] Follow our [Code of Conduct](https://github.com/eslint-stylistic/eslint-stylistic/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://eslint.style/contribute/guide).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### Describe the bug

After upgrading from 2.6.5 I get the following error:

```
node_modules/@stylistic/eslint-plugin/dist/dts/index.d.ts:121:12 - error TS2503: Cannot find namespace 'ESLint'.

121   configs: ESLint.Plugin['configs'] & Configs
               ~~~~~~
```

My `@types/eslint` is 9.6.1.

### Reproduction

Seems pretty straight-forward, but let me know if needed, I'll make one

### Contributes

- [X] I am willing to submit a PR to fix this issue
- [X] I am willing to submit a PR with failing tests
